version: "3.8"
services:
  db:
    image: postgres:alpine
    container_name: postgres-carrinho
    ports:
        - "5432:5432"
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      
      

